name: Black Code Formatter
permissions:
  contents: write
  
on: [push, pull_request]

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or your project's version

      - name: Install Black
        run: pip install black
        
      - name: Run Black and auto-commit
        run: |
          black .
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git commit -am "Apply Black formatting"
            git push
          fi

